# Generated by Django 2.1.15 on 2020-09-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200902_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_by',
        ),
    ]
