# Generated by Django 2.1.15 on 2020-08-23 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
                ('addres1', models.CharField(default='', max_length=100)),
                ('addres2', models.CharField(default='', max_length=100)),
                ('addres3', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=10)),
                ('country', models.CharField(default='', max_length=3)),
                ('zip_code', models.CharField(default='', max_length=10)),
                ('phone', models.CharField(default='', max_length=12)),
                ('mobile', models.CharField(default='', max_length=12)),
                ('webSite', models.URLField(default='')),
                ('delivery_addres', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
