# Generated by Django 2.1.15 on 2020-08-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='delivery_addres',
            field=models.BooleanField(default='False'),
        ),
    ]
