# Generated by Django 2.1.15 on 2020-07-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('airport_id', models.AutoField(primary_key=True, serialize=False)),
                ('airport', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=64)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'airports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_id', models.ForeignKey('Flights', on_delete=models.CASCADE)),
                ('pax', models.IntegerField(db_column='PAX')),
                ('flight_date', models.DateTimeField()),
                ('status', models.CharField(max_length=3)),
                ('created', models.DateTimeField()),
                ('author', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure', models.ForeignKey('Airports', on_delete=models.CASCADE, name='departure')),
                ('arrival', models.ForeignKey('Airports', on_delete=models.CASCADE, name='arrival')),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'flights',
                'managed': False,
            },
        ),
    ]
